[package]
name = "petal-decomposition"
version = "0.1.0"
description = "Principal component analysis (PCA)."
readme = "README.md"
homepage = "https://github.com/petabi/petal-decomposition"
repository = "https://github.com/petabi/petal-decomposition"
license = "Apache-2.0"
keywords = ["pca", "dimensionality-reduction", "decomposition", "matrix"]
categories = ["mathematics", "science"]
authors = ["Min Kim <msk@dolbo.net>"]
edition = "2018"
exclude = ["./github"]

[badges]
codecov = { repository = "petabi/petal-decomposition", service = "github" }

[dependencies]
itertools = "0.9"
ndarray = "0.13"
ndarray-linalg = { version = "0.12", features = ["intel-mkl"] }
num = "0.2"
thiserror = "1"

[dev-dependencies]
float-cmp = "0.8"
