[package]
name = "petal-decomposition"
version = "0.2.0"
description = "Principal component analysis (PCA)."
readme = "README.md"
homepage = "https://github.com/petabi/petal-decomposition"
repository = "https://github.com/petabi/petal-decomposition"
license = "Apache-2.0"
keywords = ["pca", "matrix", "decomposition", "dimensionality"]
categories = ["mathematics", "science"]
authors = ["Min Kim <msk@dolbo.net>"]
edition = "2018"
exclude = ["./github"]

[badges]
codecov = { repository = "petabi/petal-decomposition", service = "github" }

[package.metadata.docs.rs]
no-default-features = true

[features]
default = ["intel-mkl"]

intel-mkl = ["ndarray-linalg/intel-mkl"]
netlib = ["ndarray-linalg/netlib"]
openblas = ["ndarray-linalg/openblas"]

[dependencies]
itertools = "0.9"
lapacke = "0.2"
ndarray = "0.13"
ndarray-linalg = "0.12"
num = "0.2"
rand = "0.7"
rand_distr = "0.2"
thiserror = "1"

[dev-dependencies]
approx = "0.3"
rand_chacha = "0.2"
